### ISSUE TITLE
Telemetry board can accidently shutdown entire system

### ISSUE THREAD

**Issue by jamessynge** [panoptes/PACE#1]
I ran `head /dev/ttyACM0` to see what the telemetry board was printing out. After seeing a line of output I entered Ctrl-C to kill `head`. Either immediately or within a second my entire PANOPTES unit shut down, i.e. all of the power board relays were opened. The power supply was still producing 12V (green LED still glowing), and the telemetry board was receiving 12V (the blue LED on the board was still glowing). I failed to remember to hit the Arduino reset button so see if it was still responsive.

Why did this happen? It seems hard to explain as the `head` command is reading from the pseudo-tty device, but not writing to it, so couldn't have sent a shutdown command. So, it seems likely that closing the pseudo-tty propagated some how to the Arduino. What happened then is unclear to me.

**Comment by jamessynge** [comment]
I've reviewed the PACE/telemetry_board code, and have a partial theory for the cause of the problem...

I don't understand how this could be, but when I hit Ctrl-C to kill `head /dev/ttyACM0` it might be that Serial.available() returned non-zero. If that happened, but there really wasn't any valid input (e.g. just a newline, or some such), then eventually Serial.parseInt() will timeout (defaults to 1 second). When it does so, it returns 0 (there isn't any indication that a timeout occurred).

Unfortunately the value 0 is treated as the TURN OFF ALL RELAYS signal. Yikes.

I suggest that we promptly change the protocol (message format) which PACE/telemetry_board listens for to be something a bit more robust, even if just replacing 0 with 9. But I'd suggest we move away from parseInt, which some Arduino forum posts indicate is problematic due to just this kind of problem.

@wtgee Can you point me to the existing code that sends the relay commands to PACE?

**Comment by wtgee** [comment]
Wow, great find @jamessynge , thanks! And while I can very much see this happening have you been able to replicate it at all? Regardless, I think you are correct we should get the default changed.

Since the telemetry board is designed to keep power we should also just write in a toggle function like the computer has, so it stays down for 30 seconds and then comes back up.

Anyway, the code in the [telemetry_board](https://github.com/panoptes/PACE/blob/develop/telemetry_board/telemetry_board.ino#L101)
 should change. The [PEAS Shell](https://github.com/panoptes/PEAS/blob/develop/bin/peas_shell#L155) makes some toggle calls that interact with the arduino. I'll have to look over it to think if I could send it to that state.
